import type { Metadata } from "next";
import { Fira_Sans, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "../components/global/navbar";
import { Loader2 } from "lucide-react";
import { Suspense } from "react";
import Footer from "../components/global/footer";
import { ThemeProvider } from "next-themes";
import Background from "@/components/global/background";


const firaSans = Fira_Sans({
  variable: "--font-fira-sans",
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${firaSans.variable} ${poppins.variable} antialiased min-h-screen `}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Suspense
            fallback={
              <div className="min-h-[calc(100vh-64px)] w-full flex flex-col items-center justify-center">
                <Loader2 className="animate-spin" />
              </div>
            }
          >


            <Navbar />
            <div className="relative">
              <Background />
              {children}
            </div>
            <Footer />
          </Suspense>
        </ThemeProvider>
      </body>
    </html>
  );
}
